### ISSUE TITLE
Build breaks in Docker node:14 container

### ISSUE THREAD

**Issue by morewings** [pocka/storybook-addon-turbo-build#18]
### Description of the bug

I tried to use this plugin with GitLab CI with official `node:14` Docker image (https://hub.docker.com/_/node/) 
Build breaks with the following error
```
$ node --max-old-space-size=4096 $(yarn bin)/build-storybook -c .storybook -o static -s public
internal/modules/cjs/loader.js:905
  throw err;
  ^
Error: Cannot find module '/builds/olxeu/pwa/shared/olx-ui-library/node_modules/.bin/build-storybook'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
error Command failed with exit code 1.
```

### How to reproduce the bug?

To reproduce, run this configuration inside `node:14` docker

```js
const path = require('path');

module.exports = {
    webpackFinal: (config) => {
        config.resolve.alias = {
            ...config.resolve.alias,
            "@": path.resolve(__dirname, "../src/"),
        };
        return config;
    },
    stories: [
        "../src/**/*.stories.mdx",
        "../src/**/*.stories.@(js|jsx|ts|tsx)"
    ],
    addons: [
        '@storybook/addon-essentials',
        '@storybook/addon-knobs',
        '@storybook/addon-links',
        '@storybook/addon-a11y',
        'storybook-addon-themes',
        {
            name: "storybook-addon-turbo-build",
            options: {
                optimizationLevel: 1,
            },
        },
    ]
};
```

### Expected behaviour

It should build.

### Optimization level

1

### Addon version

1.0.1

### Storybook version

6.3.8

**Comment by pocka** [comment]
@morewings Does the command work if you comment out the addon?

From seeing the stack trace, I think the error just complains about the absence of the `build-storybook` script file. Missing `yarn install` in a build pipeline and Adding a `--production` flag to the install command often causes this error.

**Comment by morewings** [comment]
@pocka It works without this plugin (believe me, I've spent a lot of time fixing our pipeline). Also works with this plugin locally on macOS. I think it's something about Docker image specifics.

**Comment by morewings** [comment]
@pocka here is our build file. `node_modules` folder is created at `setup-environment` step. 

```yaml
image: node:14
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - .yarn/
        - .npmrc
        - node_modules/
        - static/
variables:
    GIT_DEPTH: "1000"

stages:
    - setup
    - build
    - test library
    - deploy
    - release

# Set up registry to publish and get dependencies
setup-environment:
    stage: setup
    script:
        - rm -rf .npmrc
        - yarn install --cache-folder .yarn
    only:
        - merge_requests
        - master
        - alpha
        - beta

# Runs after merge to build a Storybook assets. Needed only for AWS deploy
build-storybook:
    stage: build
    artifacts:
        paths:
            - static/
    script:
        - yarn run s:build
    only:
        - master
        - merge_requests

```
